package: base_quality_check
version: 1.3.2
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/base_quality_check
compile: true
page:
  title: Base Quality Check
  icon: rex-icon fa-check check
  perm: admin
  live_mode: false
  block: base_addon  
  subpages:
    frontend:   
      title: Frontend
    backend:   
      title: Backend   
    live:   
      title: Live           
    readme:
        title: Info
        subPath: README.md
        itemclass: pull-right
    changelog:
        title: Changelog
        subPath: CHANGELOG.md
        itemclass: pull-right        

requires:
  redaxo: '^5.15'
  yform: '^4.2.1'

installer_ignore:
    - .git
    - preview
    - .github
    - .gitignore
    - .gitattributes
